name = "war-token-api"
main = "src/index.js" # Asegúrate de que tu código esté en la carpeta /src
compatibility_date = "2024-04-01"

# Esto le dice a Cloudflare que no hay un comando de construcción (Build)
[build]
command = "" 

[[kv_namespaces]]
binding = "WAR_STORAGE"
id = "TU_ID_DE_KV_AQUI" # Pega aquí el ID que copiaste antes
