name = "war-token-api"
main = "src/index.js"
compatibility_date = "2024-04-01"

# Variables de entorno para el contrato
[vars]
CONTRACT_ADDRESS = "0x0000000000000000000000000000000000000000"
NETWORK = "BNB_SMART_CHAIN"

# Configuración de la base de datos de precios (KV)
[[kv_namespaces]]
binding = "WAR_STORAGE"
id = "PEGAR_AQUI_EL_ID_DE_TU_KV"
