name = "war-token-api"
main = "src/index.js"
compatibility_date = "2024-04-01"

# Configuración de la base de datos KV
[[kv_namespaces]]
binding = "WAR_STORAGE"
id = "450a4812d97d4038a1891b38529159b9"

# Desactivar comandos de build manuales para evitar el error de las 19:46
[build]
command = ""
